services:
  bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "main.py"]
    restart: unless-stopped
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_ARGS: "--save 60 1"
volumes:
  redis_data:
