services:
  bot:
    build:
      context: .
    volumes:
      - .:/app
    command: ["python", "main.py"]
    restart: unless-stopped
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
